export const useIcon = () => {
    return {
        home: 'i-heroicons-home',
        edit: 'i-heroicons-pencil-square',
        clipboard: 'i-heroicons-clipboard',
        copy: 'i-heroicons-outline-duplicate',
        infoCircle: 'i-heroicons-information-circle',
        exclamationCircle: 'i-heroicons-exclamation-circle',
        trash: 'i-heroicons-trash',
        xCircle: 'i-heroicons-x-circle',
        print: 'i-heroicons-printer',
        refresh: 'i-heroicons-outline-refresh',
        calendar: 'i-heroicons-outline-calendar',
        check: 'i-material-symbols-check',
        drop: 'i-ph-drop',
        add: 'i-heroicons-plus',
        minus: 'i-heroicons-minus',
        moon: 'i-heroicons-moon-20-solid',
        sun: 'i-heroicons-sun-20-solid',
        customer: 'i-streamline-information-desk-customer',
        staff: 'i-clarity-employee-group-solid',
        material: 'i-lets-icons-materials',
        setting: 'i-carbon-settings-edit',
        list: 'i-fluent-mdl2-task-list',
        avatar: 'i-carbon-user-avatar',
        stack: 'i-heroicons-square-3-stack-3d',
        upload: 'i-heroicons-cloud-arrow-up',
        search: 'i-heroicons-magnifying-glass-20-solid',
        link: 'i-heroicons-link',
        wallet: 'i-uit-wallet',
        invoice: 'i-hugeicons-invoice-03',
        tool1: 'i-material-symbols-tools-pliers-wire-stripper-outline',
        tool2: 'i-et-tools',
        shock: 'i-solar-shock-absorber-broken',
        diamondHard: 'i-game-icons-diamond-hard',
        diamond: 'i-basil-diamond-outline'

    }
}
